YOU_TOXIC = '../data_set/youtoxic_english_1000.csv'
HAT_EVAL_TRAIN = '../data_set/hateval2019_en_train.csv'
HAT_EVAL_TEST = '../data_set/hateval2019_en_test.csv'
HAT_EVAL_DEV = '../data_set/hateval2019_en_dev.csv'
HAT_EVAL = '../data_set/hateval2019_en_convinado.csv'
HAT_EVAL_BAL = '../data_set/hateval2019_en_convinado_balanceado.csv'
YOU_TOXIC_BAL = '../data_set/youtoxic_english_1000_balanceado.csv'